name: CI/CD Pipeline - .NET WebForms

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0' # Ajusta la versión si usas .NET Framework clásico con MSBuild, o déjalo si usas SDK moderno

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar solución
        run: dotnet build --configuration Release --no-restore

      - name: Ejecutar Pruebas Unitarias
        run: dotnet test TestProducto/TestProductocsproj --configuration Release --no-build

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14.8'

      - name: Instalar dependencias de pruebas Python
        run: |
          python -m pip install --upgrade pip
          pip install -r pruebas/requirements.txt

      - name: Ejecutar Pruebas Automatizadas
        run: pytest pruebas/