name: Test and Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js (para ejecutar Newman)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Newman
        run: npm install -g newman

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Compilar e Iniciar servidor local
        run: |
          dotnet build
          dotnet run --project Crud.WebForm/Crud.WebForm.csproj --urls "https://localhost:44373" &
        env:
          ASPNETCORE_ENVIRONMENT: "Development"

      - name: Esperar a que el servidor esté activo
        run: npx wait-on https://localhost:44373 --timeout 30000

      - name: Ejecutar Pruebas de Postman con Newman
        run: |
          newman run pruebas_humo_api.json \
            --env-var "BASE_URL_SCHEME=https" \
            --env-var "BASE_URL_HOST=localhost:44373" \
            --insecure